import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  StatusBar,
  TouchableOpacity,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { DN, FontFamily, FontSize, Space, Radius } from '@/constants/design-tokens';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { PrimaryButton } from '@/components/ui/PrimaryButton';
import { MOCK_REVIEW, MOCK_PROJECTS } from '@/lib/mock-data';

function ScoreGauge({
  label,
  score,
  color = DN.cyan,
}: {
  label: string;
  score: number;
  color?: string;
}) {
  return (
    <View style={styles.gaugeCard}>
      <View style={styles.gaugeBar}>
        <View
          style={[styles.gaugeFill, { width: `${score}%`, backgroundColor: color }]}
        />
      </View>
      <View style={styles.gaugeInfo}>
        <Text style={styles.gaugeLabel}>{label}</Text>
        <Text style={[styles.gaugeScore, { color }]}>{score}</Text>
      </View>
    </View>
  );
}

export default function AIReviewScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const insets = useSafeAreaInsets();

  const project = MOCK_PROJECTS.find((p) => p.id === id);
  const review = MOCK_REVIEW; // Mock: always show the same review for demo

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={[
        styles.content,
        { paddingTop: insets.top + Space.base },
      ]}
      showsVerticalScrollIndicator={false}
    >
      <StatusBar barStyle="light-content" backgroundColor={DN.bg} />

      {/* Back Button */}
      <TouchableOpacity
        style={styles.backBtn}
        onPress={() => router.back()}
        activeOpacity={0.7}
      >
        <Feather name="arrow-left" size={20} color={DN.textSecondary} />
        <Text style={styles.backLabel}>Back</Text>
      </TouchableOpacity>

      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerIcon}>
          <Feather name="zap" size={24} color={DN.cyan} />
        </View>
        <Text style={styles.title}>AI Review</Text>
        <Text style={styles.subtitle}>
          {project?.title || 'Project'} • Generated{' '}
          {new Date(review.generated_at).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
          })}
        </Text>
      </View>

      {/* Overall Score */}
      <View style={styles.overallCard}>
        <Text style={styles.overallLabel}>OVERALL SCORE</Text>
        <View style={styles.overallScoreRow}>
          <Text style={styles.overallNumber}>{review.overall_score}</Text>
          <Text style={styles.overallMax}>/100</Text>
        </View>
        <View style={styles.overallBar}>
          <View
            style={[
              styles.overallBarFill,
              { width: `${review.overall_score}%` },
            ]}
          />
        </View>
      </View>

      {/* Category Scores */}
      <SectionHeader title="Breakdown" icon="bar-chart-2" />
      <View style={styles.card}>
        <ScoreGauge label="Code Quality" score={review.code_quality} color="#52c41a" />
        <ScoreGauge label="Architecture" score={review.architecture} color="#6366f1" />
        <ScoreGauge label="Innovation" score={review.innovation} color="#faad14" />
        <ScoreGauge label="Documentation" score={review.documentation} color="#f5222d" />
      </View>

      {/* Strengths */}
      <SectionHeader title="Strengths" icon="thumbs-up" />
      <View style={styles.card}>
        {review.strengths.map((s, i) => (
          <View key={i} style={styles.listItem}>
            <View style={[styles.listDot, { backgroundColor: '#52c41a' }]} />
            <Text style={styles.listText}>{s}</Text>
          </View>
        ))}
      </View>

      {/* Suggestions */}
      <SectionHeader title="Suggestions" icon="message-circle" />
      <View style={styles.card}>
        {review.suggestions.map((s, i) => (
          <View key={i} style={styles.listItem}>
            <View style={[styles.listDot, { backgroundColor: DN.cyan }]} />
            <Text style={styles.listText}>{s}</Text>
          </View>
        ))}
      </View>

      {/* Data Source Note */}
      <View style={styles.noteCard}>
        <Feather name="info" size={14} color={DN.cyan} style={{ marginRight: Space.sm }} />
        <Text style={styles.noteText}>
          This review was generated by ProjectDNA's AI analysis engine. Results are suggestions and should be used as guidance.
        </Text>
      </View>

      {/* Back to Project */}
      <PrimaryButton
        title="Back to Project"
        variant="secondary"
        icon="arrow-left"
        onPress={() => router.back()}
        style={{ marginTop: Space.base }}
      />

      <View style={{ height: Space['3xl'] }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: DN.bg },
  content: { paddingHorizontal: Space.lg, paddingBottom: Space['4xl'] },

  // Back
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: Space.sm, marginBottom: Space.lg },
  backLabel: { fontSize: FontSize.md, fontFamily: FontFamily.medium, color: DN.textSecondary },

  // Header
  header: { alignItems: 'center', marginBottom: Space.xl },
  headerIcon: {
    width: 56, height: 56, borderRadius: 28,
    backgroundColor: DN.cyan + '1a',
    borderWidth: 1, borderColor: DN.cyan + '33',
    alignItems: 'center', justifyContent: 'center',
    marginBottom: Space.md,
  },
  title: { fontSize: FontSize['2xl'], fontFamily: FontFamily.bold, color: DN.textPrimary },
  subtitle: { fontSize: FontSize.md, fontFamily: FontFamily.regular, color: DN.textMuted, marginTop: Space.xs, textAlign: 'center' },

  // Overall
  overallCard: {
    backgroundColor: DN.bgCard, borderRadius: Radius.xl,
    borderWidth: 1, borderColor: DN.border,
    padding: Space.xl, alignItems: 'center',
    marginBottom: Space.xl,
  },
  overallLabel: { fontSize: FontSize.xs, fontFamily: FontFamily.mono, fontWeight: '700', color: DN.textMuted, letterSpacing: 1.5, marginBottom: Space.sm },
  overallScoreRow: { flexDirection: 'row', alignItems: 'baseline' },
  overallNumber: { fontSize: 64, fontFamily: FontFamily.monoBold, color: DN.cyan },
  overallMax: { fontSize: FontSize.xl, fontFamily: FontFamily.mono, color: DN.textMuted, marginLeft: 4 },
  overallBar: { width: '100%', height: 8, backgroundColor: DN.bgElevated, borderRadius: 4, overflow: 'hidden', marginTop: Space.md },
  overallBarFill: { height: '100%', backgroundColor: DN.cyan, borderRadius: 4 },

  // Card
  card: {
    backgroundColor: DN.bgCard, borderRadius: Radius.lg,
    borderWidth: 1, borderColor: DN.border,
    padding: Space.base, marginBottom: Space.xl,
  },

  // Gauge
  gaugeCard: { marginBottom: Space.md },
  gaugeBar: { height: 6, backgroundColor: DN.bgElevated, borderRadius: 3, overflow: 'hidden', marginBottom: Space.xs },
  gaugeFill: { height: '100%', borderRadius: 3 },
  gaugeInfo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  gaugeLabel: { fontSize: FontSize.md, fontFamily: FontFamily.medium, color: DN.textSecondary },
  gaugeScore: { fontSize: FontSize.md, fontFamily: FontFamily.monoBold },

  // Lists
  listItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: Space.sm },
  listDot: { width: 6, height: 6, borderRadius: 3, marginTop: 7, marginRight: Space.md },
  listText: { flex: 1, fontSize: FontSize.md, fontFamily: FontFamily.regular, color: DN.textSecondary, lineHeight: 20 },

  // Note
  noteCard: {
    flexDirection: 'row', alignItems: 'flex-start',
    backgroundColor: DN.cyanDark, borderRadius: Radius.md,
    borderWidth: 1, borderColor: DN.borderFocus,
    padding: Space.md,
  },
  noteText: { flex: 1, fontSize: FontSize.sm, fontFamily: FontFamily.regular, color: DN.textSecondary, lineHeight: 18 },
});
